const Body = props=>{
	return (
		<div>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			<p>body</p>
			
		</div>
	);
};

export default Body;